<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="28.216" timestamp="2024-10-29T12:31:04.628155+01:00" hostname="LAPTOP-RF75R21I"><testcase classname="" name="tests.test_api" time="0.000"><error message="collection failure">test_api.py:14: in &lt;module&gt;
    from src.app.api import (
..\src\app\api.py:31: in &lt;module&gt;
    with open(rating_models_api, "w") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'metrics\\model_stats_api.json'</error></testcase></testsuite></testsuites>